// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.TradeVolumes.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetPairTradeVolumeResponse
    {
        /// <summary>
        /// Initializes a new instance of the AssetPairTradeVolumeResponse
        /// class.
        /// </summary>
        public AssetPairTradeVolumeResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPairTradeVolumeResponse
        /// class.
        /// </summary>
        public AssetPairTradeVolumeResponse(double baseVolume, double quotingVolume, string clientId = default(string), string walletId = default(string), string assetPairId = default(string))
        {
            ClientId = clientId;
            WalletId = walletId;
            AssetPairId = assetPairId;
            BaseVolume = baseVolume;
            QuotingVolume = quotingVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletId")]
        public string WalletId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseVolume")]
        public double BaseVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuotingVolume")]
        public double QuotingVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
